version: '3'
services:
  web:
    image: nginx
    container_name: mycomposenginx
    ports:
    - "8080:80"
    volumes:
    - ./app:/usr/share/nginx/html
    environment:
    - NGINX_HOST=dede.teste
    - NGINX_PORT=80

networks:
  minha-rede:
    driver: bridge

