# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
<<<<<<<< HEAD:Criando_um_Deploy_de_uma_Aplicação/Vagrantfile
  "master" => {"memory" => "2048", "cpu" => "2", "ip" => "210", "image" => "bento/ubuntu-22.04"},
  "worker01" => {"memory" => "1024", "cpu" => "1", "ip" => "220", "image" => "bento/ubuntu-22.04"},
  "worker02" => {"memory" => "512", "cpu" => "1", "ip" => "220", "image" => "bento/ubuntu-22.04"}
========
  "master" => {"memory" => "2048", "cpu" => "2", "ip" => "210", "image" => "bento/ubuntu-22.04"}
  "worker01" => {"memory" => "1024", "cpu" => "1", "ip" => "220", "image" => "bento/ubuntu-22.04"}
>>>>>>>> 3b1c6fdc3903f347135fa677dd5058859f30ad34:Cluster-Swarm/Vagrantfile
}


Vagrant.configure("2") do |config|
  
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "public_network", ip: "10.0.0.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]

      end
      machine.vm.provision "shell", path: "docker.sh"
    
   

      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end

